### ISSUE TITLE
Bug in profile display

### ISSUE THREAD

**Issue by salliewalecka** [MichaelACohen/cs135#1]
I pulled your stuff and it introduced a bug in the display.  Right now, I have it that you can click a follower and followee and it will send you to the profile page of the follower/ee using $_GET.  That page is slightly altered.  However, now, once it does that, everything else displayed is now under the account of the follower/ee (ex. if I am logged in as Sallie and click to michael's profile, I see that fine, but if I go to check my followers, I really see michael's followers)

Also the Delete buttons should only be on the user's prof page and they are inoperable as of present

**Comment by MichaelACohen** [comment]
so, what we could do is just pass the user id in the url for all the profile pages, follower pages, and so on. so for example if we want to look at your profile (userid=1) we would go to "profile.php?id=1". so in profile.php we would see what the id is and then display the right videos accordingly

**Comment by MichaelACohen** [comment]
does that sound ok?

**Comment by MichaelACohen** [comment]
so yeah you are doing that already for if you are looking at someone else's profile but we can just do that for everything

**Comment by MichaelACohen** [comment]
let me know if you pull and still have this problem
